apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-helm

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/name=nginx"
    path: deployment-patch.yaml
