apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - networkpolicy.yaml
  - pdb.yaml
  - serviceaccount.yaml
  - svc.yaml
  - tls-secret.yaml
  - ingress.yaml