apiVersion: v1
kind: Service
metadata:
  name: login-app
spec:
  selector:
    app: login-app
  type: NodePort   # Bisa diakses dari luar cluster via NodePort
  ports:
    - port: 8080       # Port di service
      targetPort: 8080 # Port container
      nodePort: 30080  # Port untuk akses dari host
